import { defineConfig } from 'vite'
import tailwindcss from '@tailwindcss/vite'
import { resolve } from 'path'

export default defineConfig({
  plugins: [tailwindcss()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        security: resolve(__dirname, 'security.html'),
        contact: resolve(__dirname, 'contact.html'),
        terms: resolve(__dirname, 'terms.html'),
        privacy: resolve(__dirname, 'privacy.html'),
        download: resolve(__dirname, 'download.html'),
        'docs-index': resolve(__dirname, 'docs/index.html'),
        'docs-getting-started': resolve(__dirname, 'docs/getting-started.html'),
        'docs-login-setup': resolve(__dirname, 'docs/login-setup.html'),
        'docs-ai-guide': resolve(__dirname, 'docs/ai-guide.html'),
        'docs-email-reply': resolve(__dirname, 'docs/email-reply.html'),
        'docs-blog-writing': resolve(__dirname, 'docs/blog-writing.html'),
        'docs-review-reply': resolve(__dirname, 'docs/review-reply.html'),
        'docs-line-message': resolve(__dirname, 'docs/line-message.html'),
        'docs-token-management': resolve(__dirname, 'docs/token-management.html'),
        'docs-hub': resolve(__dirname, 'docs/hub.html'),
        'docs-hub-internal-knowledge': resolve(__dirname, 'docs/hub-internal-knowledge.html'),
        'docs-hub-team': resolve(__dirname, 'docs/hub-team.html'),
        'docs-ai-knowledge': resolve(__dirname, 'docs/ai-knowledge.html'),
        'docs-content-generator': resolve(__dirname, 'docs/content-generator.html'),
        'docs-workflow': resolve(__dirname, 'docs/workflow.html'),
        'docs-ai-knowledge-categories': resolve(__dirname, 'docs/ai-knowledge-categories.html'),
        'docs-blog-content-generation': resolve(__dirname, 'docs/blog-content-generation.html'),
        'docs-sns-content-generation': resolve(__dirname, 'docs/sns-content-generation.html'),
        'docs-line-content-generation': resolve(__dirname, 'docs/line-content-generation.html'),
        'docs-file-upload-tips': resolve(__dirname, 'docs/file-upload-tips.html'),
        'docs-generation-history': resolve(__dirname, 'docs/generation-history.html'),
        'docs-generation-templates': resolve(__dirname, 'docs/generation-templates.html'),
        'blog-index': resolve(__dirname, 'blog/index.html'),
        'blog-why-ai-content-feels-generic': resolve(__dirname, 'blog/why-ai-content-feels-generic.html'),
        'blog-sns-workflow-for-shops': resolve(__dirname, 'blog/sns-workflow-for-shops.html'),
        'blog-beauty-salon-product-sns': resolve(__dirname, 'blog/beauty-salon-product-sns.html'),
        'blog-ai-content-3-steps-to-authenticity': resolve(__dirname, 'blog/ai-content-3-steps-to-authenticity.html'),
        'blog-blog-sns-line-from-one-theme': resolve(__dirname, 'blog/blog-sns-line-from-one-theme.html'),
        'blog-restaurant-daily-menu-ai': resolve(__dirname, 'blog/restaurant-daily-menu-ai.html'),
        'blog-company-info-5-categories': resolve(__dirname, 'blog/company-info-5-categories.html'),
        'blog-professionals-newsletter-ai': resolve(__dirname, 'blog/professionals-newsletter-ai.html'),
        'blog-solo-entrepreneur-ai-roadmap': resolve(__dirname, 'blog/solo-entrepreneur-ai-roadmap.html'),
        'blog-general-vs-company-ai': resolve(__dirname, 'blog/general-vs-company-ai.html'),
        'blog-what-to-delegate-to-ai-2026': resolve(__dirname, 'blog/what-to-delegate-to-ai-2026.html'),
        'blog-ai-team-meeting-15min': resolve(__dirname, 'blog/ai-team-meeting-15min.html'),
        'blog-ai-privacy-checklist': resolve(__dirname, 'blog/ai-privacy-checklist.html'),
        'blog-monthly-content-calendar-ai': resolve(__dirname, 'blog/monthly-content-calendar-ai.html'),
        'blog-company-ai-usage-rules': resolve(__dirname, 'blog/company-ai-usage-rules.html'),
        'blog-company-info-ai-boundaries': resolve(__dirname, 'blog/company-info-ai-boundaries.html'),
      },
    },
  },
})
